def build(bld):
    bld.env['LIB'] = ['mkl_intel_lp64', 'mkl_sequential', 'mkl_core', 'pthread', 'gsl']
    for x in 'special spline error'.split():
        bld(target=x, source='%s.pyx' % x,
            features='c fc pyext cshlib',
            use='NUMPY'
            )
